language: objective-c

before_script:
  - scripts/ci/travis/instruments-auth.sh
  - gem install xcpretty --no-document
  - gem install run_loop --no-document

script:
  - make clean
  - make framework
  - make frank
  # Dylib creation is allowed by Xcode 6, but it requires
  # code-signing which is not easy to set up on Travis CI.
  #- make dylibs
  #- make all
  - scripts/test/run-chou-tests.rb
  - scripts/test/xctest.rb

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - karl.krukow@xamarin.com
    on_success: change
    on_failure: always
